---
.travis.yml:
  unmanaged: true

Gemfile:
  optional:
    ':development':
      - gem: hocon
        version: '~> 1.1'

appveyor.yml:
  delete: true

.gitlab-ci.yml:
  unmanaged: true

Rakefile:
  requires:
    - puppet-lint/tasks/puppet-lint
