---
.travis.yml:
  unmanaged: true

Gemfile:
  optional:
    ':development':
      - gem: hocon
        version: '~> 1.1'
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"


appveyor.yml:
  delete: true

.gitlab-ci.yml:
  unmanaged: true

Rakefile:
  requires:
    - puppet-lint/tasks/puppet-lint
